/**
 * Visual Display Label Utility
 * Preaches raw-looking internal keys with elegant, human-readable Fieldtrip copy.
 */

const ACTION_LABELS: Record<string, string> = {
  // Admin & Actions keys
  CONVENE_AUDIT_HQ: "Open Review HQ",
  DEPLOY_SUMMER_SURGE: "Deploy Heatwave Receipts",
  DEPLOY_HEATWAVE_RECEIPTS: "Deploy Heatwave Receipts",
  AUTHOR_NEW_MISSION: "Author New Mission",
  SEARCH_MISSION_REGISTRY: "Search mission registry",
  FIELD_TYPE: "Field Type",
  SUMMER_SURGE: "Heatwave Receipts",
  AUDIT_HQ: "Review HQ",
  MISSION_REGISTRY: "Mission Registry",
  USER_PROFILE: "User Profile",
  STARTER_SIGNALS: "Starter Signals",
  PROOF_REVIEW: "Proof Review",
  ADMIN_REVIEW: "Admin Review",
  OPS_REGISTRY_V2: "Ops Registry V2",
  SYSTEM_CONFIG: "System Config",
  TOTAL_MISSIONS: "Total Missions",
  ACTIVE_SOCIAL: "Active Social",
  ACTIVE_EXPLORE: "Active Explore",
  CREW_REQUIRED: "Crew Required",
  FINALIZE_WEEK_VOTES: "Finalize Week Votes",
  ADMIN_ACTION_LOG: "Admin Action Log",
  INCOMING_QUEUE: "Incoming Queue",
  CONFESSION_SELF: "Confession Self",
  PERSONA_IDENTIFIED: "Persona Identified",
  BABE_VERIFIED: "Babe Verified",
  PRISM_UNLOCKED: "Prism Unlocked",
  SPLASH_READY: "Splash Ready",
  ASSIGNED_UNIT: "Assigned Unit",
  RE_AUDIT_SIGNAL: "Re-Audit Signal",
  IMAGE_FETCH_FAILED: "Image Fetch Failed",
  ENTRY_NOT_FOUND: "Entry Not Found",
  NO_IMAGE_IN_ENTRY: "No Image In Entry",
  CHALLENGE_NOT_FOUND: "Challenge Not Found",
  FILTER_MISMATCH: "Filter Mismatch",
  USER_HIDDEN: "User Hidden",
  REASON_REQUIRED: "Reason Required",
  CURRENT_CYCLE: "Current Cycle",
  PROTOCOL_HISTORY: "Protocol History",
  VOTE_ACCESS: "Vote Access",
  VIEW_DEMO_OPS: "View Demo Ops",
  FIELD_HQ_BOARD: "Field HQ Board",
  REVOKE_CLEARANCE: "Revoke Clearance",
  GRANT_ADMIN_ACCESS: "Grant Admin Access",
  MISSION_DRAW_SYSTEM: "Mission Draw System",
  ACTIVE_DECK: "Active Deck",
  NOT_STARTED: "Not Started",
  IN_PROGRESS: "In Progress",
  PENDING_REVIEW: "Pending Review",
  NEEDS_MORE_PROOF: "Needs More Proof",
  REJECTED_RETRY_AVAILABLE: "Rejected (Retry Available)",
  COMPLETE: "Complete",
  MISSION_LIMIT_REACHED: "Mission Limit Reached",
  UPLINK_READY_FOR_HAND_OFF: "Uplink Ready for Hand-off",
  ACTIVE_MISSION_SIGNAL: "Active Mission Signal",
  NEW_MISSION_DRAWN: "New Mission Drawn",
  SECURE_PROTOCOL: "Secure Protocol",
  REPAIRING_SYSTEM: "Repairing System",
  REPAIR_GLOBAL_CONFIG: "Repair Global Config",
  LENS_CAPTURE: "Lens Capture",
  FIELD_DATA: "Field Data",
  ANON_AGENT: "Anon Agent",
  REQUEST_FIELD_CHECK: "Request Field Check",
  REQUIRED_ARTIFACTS: "Required Artifacts",
  ZINE_READY: "Zine Ready",
  INTEL_REQUEST: "Intel Request",
  COMPLETED: "Completed",
  START_MISSION: "Start Mission",
  DECK_EXHAUSTED: "Deck Exhausted",
  UPLINK_RESTRICTED: "Uplink Restricted",
  TAP_TO_DRAW_MISSION: "Tap to Draw Mission",
  TRANSMITTING: "Transmitting",
  REASON_FOR_CHECK: "Reason for Check",
  FIELD_JOURNAL_NOTE: "Field Journal Note",
  INITIATE_FIELD_CHECK: "Initiate Field Check",
  CHECK_TRANSMITTED: "Check Transmitted",
  RETURN_TO_ARCHIVE: "Return to Archive",
  DISPATCH_ANALYSTS: "Dispatch Analysts",
  ADMIN_BYPASS: "Admin Bypass",
  DEV_ACTIVE: "Dev Active",
  PRE_FLIGHT_SYNC: "Pre-flight Sync",
  UPLINK_LIVE: "Uplink Live",
  RESUME_MISSION: "Resume Mission",
  PROTOCOL_HIJK_ACTIVE: "Protocol Hijack Active",
  PROTOCOL_STANDBY: "Protocol Standby",
  CHAPTER_DECAL_RESTORED: "Chapter Decal Restored",
  BUREAU_CREDIT_UNLOCKED: "Bureau Credit Unlocked",
  MISSION_DETAILS: "Mission Details",
  MISSION_ARCHIVED_SUCCESS: "Mission Archived Successfully",
  MISSION_UPLINK_PENDING: "Mission Uplink Pending",
  SYSTEM_SCANNING: "System Scanning",
  READY_FOR_LAUNCH: "Ready for Launch",
  SYNCHRONIZING_DATABASE: "Synchronizing Database",
  TRIP_MGMT_BETA: "Trip Management Beta",
  BUREAU_UPLINK: "Bureau Uplink",
  BUREAU_SUCCESS: "Bureau Success",
  BUREAU_ERROR: "Bureau Error",
  HEATWAVE_RECEIPTS: "Heatwave Receipts",
  USER_MANAGEMENT: "User Management",
  ADMIN_FORCE_SIZE: "Admin Force Size",
  FILTER_BY_NAME_OR_IDENTIFIER: "Filter by name or identifier",
  ONBOARDING_PENDING: "Onboarding Pending",
  LEVEL_ADMIN: "Level: Admin",
  LEVEL_AGENT: "Level: Agent",
  ABORT_ACTION: "Abort Action",
  ACCESS_DENIED: "Access Denied",
  BALLOT_BOX_CLOSED: "Ballot Box Closed",
  SNITCH_REPORTER: "Reporter",
  TARGET_ENTRY: "Target Entry",
  OPEN_EVIDENCE: "Open Evidence",
  ACCUSATION_DETAILS: "Accusation Details",
  ALLEGATION: "Allegation",
  STATUS: "Status",
  BUREAU_STAMPED_HV: "Bureau Stamped HV",
  ADMIN_PANEL: "Admin Panel",
  MISSIONS: "Missions",
  TOKENS: "Tokens",
  UPLINK_ESTABLISHED: "Uplink Established",
  CORE_DIRECTIVE: "Core Directive",
  TRANSMISSION_RECEIVED: "Transmission Received",
  READY_FOR_DEPLOYMENT: "Ready for Deployment",
  EYE_CAPTURE: "Eye Capture",
  FIELD_NOTE: "Field Note",
  EVIDENCE: "Evidence",
  NEW_REWARD_UNLOCKED: "New Reward Unlocked",
  MATH_WIZARD_BREAKDOWN: "Math Wizard Breakdown",
  SIGNAL_OPTIMIZED: "Signal Optimized",
  SIGNAL_RESTRICTED: "Signal Restricted",
  RESEARCH_ARTIFACT: "Research Artifact",
  PROCESSING_SIGNAL: "Processing Signal...",
  FIELD_STATION: "Field Station",
  AGENT_ID: "Agent ID",
  BUREAU_LEVEL: "Bureau Level",
  WEEKLY_RANK: "Weekly Rank",
  RANK_VERIFIED: "Rank Verified",
  PROTOCOL_STANDING: "Protocol Standing",
  LOGS_VERIFIED: "Logs Verified",
  AUTHORIZED: "Authorized",
  APPROVED: "Approved",
  LOG_ENTRY: "Log Entry",
  UPLINK_DETAILS: "Uplink Details",
  SYNCHRONIZING_COLLECTION: "Syncing Collection",
  SIGNAL_ANALYSIS: "Signal Analysis",
  XP_YIELD: "XP Yield",
  NEW_TOKEN: "New Token",
  ENGAGEMENT_OPTIONS: "Options",
  AUTHENTICATION_STATION: "Auth Station",
  DRAW_CARD: "Draw Card",
  MISSION_SECURED: "Mission Secured"
};

export function getDisplayLabel(key: string): string {
  if (!key) return '';
  
  // Clean up any outer characters if present (e.g., [TRIP_MGMT_BETA] or dots/colons)
  const cleanKey = key.trim().replace(/^\[|\]$/g, '');
  
  if (ACTION_LABELS[cleanKey]) return ACTION_LABELS[cleanKey];

  if (import.meta.env.DEV) {
    console.warn("Missing display label for key:", key);
  }

  // Safe fallback conversion:
  // Convert underscores and dashes to space, format as title-case
  return cleanKey
    .toLowerCase()
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}
